#!/usr/bin/python

from sys import *
from socket import *
import select

#file filled with mcastgroup:mcastport

if len(argv) != 3: 
    print argv[0], '<if_ip> <file>'
    exit(1)

if_ip = argv[1]
socks = []

with open(argv[2]) as f:
    ips = [line.strip('\n').split(':') for line in f.readlines()]
    for (mcast_group, mcast_port) in ips :
        print 'from', if_ip, 'listen/join', mcast_group, ':', mcast_port
        mcastsock = socket(AF_INET, SOCK_DGRAM)
        mcastsock.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
        mcastsock.setsockopt(SOL_IP, IP_ADD_MEMBERSHIP, inet_aton(mcast_group)+inet_aton(if_ip))
        mcastsock.bind((mcast_group, int(mcast_port)))
        socks.append(mcastsock)

while 1:
    #ready_to_read, ready_to_write, in_error = select.select( potential_readers, potential_writers, potential_errs, timeout)
    ready_to_read, ready_to_write, in_error = select.select(socks, [], [], 1)
    for mcastsock in ready_to_read :
        data = mcastsock.recv(512)
        #print data
        print data.decode('ascii', 'ignore')
        #print data.decode("utf-8", "ignore")
        #print data.decode('base64')
